version: "3.7"

services:
  web:
    container_name: blog_web
    image: romano9533/flask_blog:latest
    build:
      context: app
      target: builder
      dockerfile: ../docker/Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    expose:
      - '5050'
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./app:/app
      - static_volume:/app/blog/static

  scheduler:
    container_name: blog_scheduler
    image: romano9533/flask_blog:latest
    entrypoint: "python3 scheduler.py"
    volumes:
      - ./app:/app
      - static_volume:/app/blog/static
    restart: always
    depends_on:
      - web

  nginx:
    container_name: blog_nginx
    restart: always
    image: nginx:latest
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/blog/static

  postgresql:
    container_name: blog_db
    restart: always
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: blog_redis
    restart: always
    image: redis
    volumes:
      - cache:/data
    ports:
      - '6379:6379'

volumes:
  postgresql:
  static_volume:
  cache: