version: "3.8"

services:
  web:
    container_name: blog_web
    image: romano9533/flask_blog:latest
    stop_signal: SIGINT
    expose:
      - "5050"
    depends_on:
      - postgresql
      - redis

  scheduler:
    container_name: blog_scheduler
    image: romano9533/flask_blog:latest
    entrypoint: "python3 scheduler.py"
    restart: always
    depends_on:
      - web

  nginx:
    container_name: blog_nginx
    restart: always
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgresql:
    container_name: blog_db
    restart: always
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: blog_redis
    restart: always
    image: redis
    volumes:
      - cache:/data
    ports:
      - "6379:6379"

volumes:
  postgresql:
  cache: